import pygame

GAME_TICK_SECOND = pygame.USEREVENT + 1
WINNER_DECLARED = pygame.USEREVENT + 2
POWER_UP_GAIN_EVENT = pygame.USEREVENT + 3
POWER_UP_DESTROY_EVENT = pygame.USEREVENT + 4
POWER_UP_QUANTUM_COLLAPSE = pygame.USEREVENT + 5
POWER_UP_QUANTUM_COLLAPSE_STOP_GLOW_LEFT = pygame.USEREVENT + 6
POWER_UP_QUANTUM_COLLAPSE_STOP_GLOW_RIGHT = pygame.USEREVENT + 7
COIN_PICKUP = pygame.USEREVENT + 8