name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: uv sync

      - run: uv run pyinstaller GravBall.spec

      - name: Package
        shell: bash
        run: |
          mkdir release

          if [ "${{ runner.os }}" = "Windows" ]; then
            cd dist
            powershell Compress-Archive -Path GravBall.exe -DestinationPath ../release/GravBall-windows.zip
          elif [ "${{ runner.os }}" = "macOS" ]; then
            cd dist
            zip -r ../release/GravBall-macos.zip GravBall
          else
            cd dist
            zip -r ../release/GravBall-linux.zip GravBall
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: release/*

  release:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release

      - uses: softprops/action-gh-release@v2
        with:
          files: release/**/*.zip